<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffrobot">

	<!-- This will include all the contents of example_include.xacro first. Go check it out! -->
	<xacro:include filename="diffrobot_include.xacro" />
	<xacro:include filename="diffrobot_gazebo.xacro" />


	<!-- This first link called "world" is empty -->
	<!-- <link name="world"></link> -->


	<!-- A simple fixed joint from our empty world link, to our base. -->
	<!-- The base origin is offset from the world origin. -->
	<!-- <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->


	<link name="base_link">
		<visual name="base_link_visual">
			<origin xyz="0 0 ${caster_radius + chassis_length/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${chassis_length}" radius="${chassis_radius}"/>
			</geometry>
			<material name="orange"/>
		</visual>

		<collision name="base_link_collision">
			<origin xyz="0 0 ${caster_radius + chassis_length/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${chassis_length}" radius="${chassis_radius}"/>
			</geometry>
		</collision>

		<visual name="base_link_caster_visual">
			<origin xyz="-${chassis_radius - caster_radius} 0 ${caster_radius}" rpy="0 0 0"/>
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
		</visual>

		<collision name="base_link_caster_collision">
			<origin xyz="-${chassis_radius - caster_radius} 0 ${caster_radius}" rpy="0 0 0"/>
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
			<surface>
				<friction>
					<ode>
						<mu>0</mu>
						<mu2>0</mu2>
						<slip1>1.0</slip1>
						<slip2>1.0</slip2>
					</ode>
				</friction>
			</surface>
		</collision>

		<xacro:inertial_cylinder radius="${chassis_radius}" length="${chassis_length}" mass="${chassis_mass}">
			<origin xyz="0 0 ${caster_radius + chassis_length/2}" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
	</link>	<!-- base_link -->


	<!-- Robot footprint -->
	<link name="base_footprint"/>

	<joint name="base_footprint_joint" type="fixed">
		<parent link="base_link"/>
		<child link="base_footprint"/>
		<origin xyz="0.0 0.0 ${-(caster_radius+chassis_length/2)}" rpy="0.0 0.0 0.0"/>
	</joint>


	<!-- wheel definition -->
	<xacro:wheel prefix="left" reflect="1.0"/>
	<xacro:wheel prefix="right" reflect="-1.0"/>


	<!-- LIDAR -->
	<link name="lidar">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder length="0.07" radius="0.105"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="file://$(find diffrobot_description)/meshes/hokuyo.dae"/>
			</geometry>
		</visual>

		<inertial>
			<mass value="1e-5" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>

	<joint name="lidar_joint" type="fixed">
		<origin xyz="0 0 ${chassis_length + caster_radius + 0.035}" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="lidar"/>
	</joint>


</robot>